version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - music-store-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/musicdb?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:latest"
    restart: always
    ports:
      - 3306:3306
    networks:
      - music-store-net
    environment:
      MYSQL_DATABASE: musicdb
      MYSQL_USER: music_one
      MYSQL_PASSWORD: music_pw
      MYSQL_ROOT_PASSWORD: music_Rpw

  localstack:
    image: localstack/localstack:1.4
    hostname: localstack
    networks:
      - music-store-net
    environment:
      SERVICES: secretsmanager,s3
      DOCKER_HOST: unix:///var/run/docker.sock
      HOST_TMP_FOLDER: /tmp/localstack
      HOSTNAME_EXTERNAL: localstack
      HOSTNAME: localstack
    ports:
      - "4566:4566"
    volumes:
      - /tmp/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - .container/localstack:/docker-entrypoint-initaws.d
    healthcheck:
      test: [
        "CMD-SHELL",
        "awslocal secretsmanager get-secret-value --secret-id secret",
        "awslocal s3api list-buckets"
      ]

networks:
  music-store-net: