CREATE TABLE MUSIC_OF_ALBUM (
    ID INT NOT NULL AUTO_INCREMENT,
    MUSIC_ID INT NOT NULL,
    ALBUM_ID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (MUSIC_ID) REFERENCES MUSIC(ID),
    FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM(ID)
) ENGINE=INNODB;
